name: Hello World

on:
    push:
        branches:
            - master1

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Say Hello
          run: |
            echo "Hello, World!"
            ls -la
            pwd
        - uses: hashicorp/setup-terraform@v3

        - run: terraform version 
